# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    if bld.path.find_resource('bgp-example.cc'):
        obj = bld.create_ns3_program('bgp-example', ['bgp', 'csma'])
        obj.source = 'bgp-example.cc'

    if bld.path.find_resource('bgp-minimal-example.cc'):
        obj = bld.create_ns3_program('bgp-minimal-example', ['bgp', 'csma', 'internet-apps'])
        sources = ['bgp-minimal-example.cc']
        if bld.path.find_resource('bgp-minimal-scenario.cc'):
            sources.append('bgp-minimal-scenario.cc')
        obj.source = sources

    obj = bld.create_ns3_program(
        'bgp-aspath-convergence-example',
        ['core', 'network', 'internet', 'csma', 'bgp'])
    obj.source = 'bgp-aspath-convergence-example.cc'
